### PR TITLE
Use json api when searching by ABN, add business_name

### PR DESCRIPTION
**Pull request by allanoneflare**
Use json api when searching by ABN, add business_name (array of known names from JSON API endpoint)

### CODE REVIEW

**Review by jywei — APPROVED** [review]
faith

**Comment by jamsi** [comment]
Oh hai.

What's going on here ...

**Comment by allanoneflare** [comment]
> Oh hai.
> 
> What's going on here ...

you're baby needs some care @jamsi

**Comment by jamsi** [comment]
Sorry I can't help. My brain is hard wired to elixir now ...

**Pull request merged**
